name: Password Protect
description: Password Protect your site with Htaccess, good for demo'ing to clients

author: Darren Moore
authorEmail: darren.m@firecreek.co.uk
authorUrl: http://www.firecreek.co.uk
